import type { ActionPresentation, CategoryPresentation, ResultTile } from "./model";

export const CATEGORIES = [
  { id: "session", label: "集中・セッション", description: "その場だけ有効にして、終われば解放", icon: "focus" },
  { id: "power", label: "電源", description: "現在の電源状態を安全に確認", icon: "power" },
  { id: "explorer", label: "ファイル表示", description: "ファイルを見分けやすくする", icon: "explorer" },
  { id: "appearance", label: "見た目", description: "Windowsとアプリの明暗を揃える", icon: "appearance" },
  { id: "games", label: "ゲーム", description: "登録したゲームを変更せずに見守る", icon: "game" },
] as const satisfies readonly CategoryPresentation[];

export const RESULT_TILES = [
  { id: "game-ready", title: "ゲームの準備を整える", description: "起動を検知し、邪魔を減らす準備をまとめます。", category: "games", icon: "game" },
  { id: "appearance", title: "見た目を変える", description: "Windowsとアプリを落ち着いた明暗へ揃えます。", category: "appearance", icon: "appearance" },
  { id: "files", title: "ファイルを見分けやすくする", description: "拡張子や隠しファイルを必要なときに表示します。", category: "explorer", icon: "explorer" },
  { id: "focus", title: "集中を途切れさせない", description: "作業中の自動スリープだけを一時的に防ぎます。", category: "session", icon: "focus" },
  { id: "power", title: "電源設定を確かめる", description: "変更せず、現在の電源プランを確認します。", category: "power", icon: "power" },
  { id: "recovery", title: "変更を元へ戻す", description: "適用履歴から、戻したい項目だけを選べます。", category: "recovery", icon: "recovery" },
] as const satisfies readonly ResultTile[];

export const STATIC_ACTIONS = [
  {
    id: "session.prevent_sleep",
    actionVersion: 1,
    name: "このモード中は自動スリープを防ぐ",
    description: "勉強、配信、長い処理の途中でPCが自動スリープへ入らないようにします。画面の常時点灯は既定で行いません。",
    audience: "作業中だけPCを起こしておきたい人向け",
    category: "session",
    tags: ["一時的", "公開API", "画面点灯なし"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: true,
    kind: "session",
    availability: "mutable",
    methodSummary: "Windows公開API SetThreadExecutionStateの専用lease",
    desiredState: "自動スリープを一時的に防ぐ（画面点灯なし）",
    detailPoints: [
      "最後のleaseを解放すると、Totonoeの要求だけを解除します。",
      "Totonoe終了時もOSが要求を解放します。",
      "他アプリのスリープ防止要求は変更しません。",
    ],
  },
  {
    id: "power.active_scheme_check",
    actionVersion: 1,
    name: "現在の電源設定を確認する",
    description: "現在アクティブな電源プランを読み取り専用で確認します。設定は変更しません。",
    audience: "ゲームや作業前に電源状態だけを確かめたい人向け",
    category: "power",
    tags: ["読み取り専用", "公開API"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "observation",
    availability: "read_only",
    methodSummary: "Windows公開Power APIによる読み取り",
    desiredState: "現在の電源プランを表示する（変更なし）",
    detailPoints: [
      "PowerGetActiveSchemeで構成値を読み取ります。",
      "OEM独自の状態は不明として表示する場合があります。",
      "読み取りのためrollback対象となる変更はありません。",
    ],
  },
  {
    id: "explorer.show_extensions",
    actionVersion: 1,
    name: "ファイルの拡張子を常に表示する",
    description: "画像、文書、実行ファイルなどの種類を名前の末尾で見分けやすくします。",
    audience: "似た名前のファイルを安全に見分けたい人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "拡張子を表示する",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "Explorerを強制再起動せず、設定変更通知で反映します。",
      "Windows Update後は再検証まで自動変更を止めます。",
    ],
  },
  {
    id: "explorer.show_hidden",
    actionVersion: 1,
    name: "隠しファイルを表示する",
    description: "通常は隠されているファイルをExplorerへ表示します。保護されたOSファイルの表示は変更しません。",
    audience: "設定ファイルを探す必要がある人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "保護OSファイル除外"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "caution",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "隠しファイルを表示する",
    detailPoints: [
      "表示されたファイルを誤って移動・削除しないよう注意が必要です。",
      "保護されたオペレーティングシステムファイルは対象外です。",
      "元々値が無ければ、復元時に削除して欠如状態へ戻します。",
    ],
  },
  {
    id: "theme.color_mode",
    actionVersion: 1,
    name: "Windowsとアプリをダーク表示にする",
    description: "Windowsのシステム面と対応アプリを、落ち着いたダーク表示へ揃えます。",
    audience: "暗い環境で明るさを抑えたい人向け",
    category: "appearance",
    tags: ["HKCU", "2項目を一括復元", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Themes\\Personalizeの2値を複合Actionとして保存・変更",
    desiredState: "Windowsと対応アプリをダーク表示にする",
    detailPoints: [
      "アプリ用とシステム用の2値をまとめてbackupします。",
      "ハイコントラストや組織ポリシーと競合する場合は変更しません。",
      "一部のアプリでは再起動後に表示が変わります。",
    ],
  },
  {
    id: "games.process_watch",
    actionVersion: 1,
    name: "登録したゲームの起動・終了を検知する",
    description: "登録済み実行ファイルの本人性を確認し、起動と終了だけを見守ります。ゲームへの注入や改変はしません。",
    audience: "ゲームごとの準備を将来自動化したい人向け",
    category: "games",
    tags: ["読み取り専用", "注入なし", "本人性確認"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "observation",
    availability: "read_only",
    methodSummary: "Toolhelp snapshot、process path、PID、creation time、file identityの照合",
    desiredState: "登録後、本人性を確認できたゲームだけを監視する（OS変更なし）",
    currentState: {
      kind: "unknown",
      label: "実行ファイル未登録",
      detail: "プロファイルで実行ファイルを登録した後に、path・作成時刻・file identityを照合します。",
    },
    detailPoints: [
      "process名だけでなく、pathと作成時刻を照合します。",
      "アクセス拒否時は未実行と推測せず、状態不明として扱います。",
      "ゲームprocessやファイルへ書き込み・注入を行いません。",
    ],
  },
] as const satisfies readonly ActionPresentation[];
