import type { ActionPresentation, CategoryPresentation, ResultTile } from "./model";

export interface EverydayFeatureGuide {
  readonly id: string;
  readonly result: string;
  readonly featureName: string;
  readonly description: string;
  readonly provider: "powertoys" | "windows";
}

export const EVERYDAY_FEATURE_GUIDES = [
  { id: "remap-keys", result: "キーを入れ替える", featureName: "Keyboard Manager", description: "使いにくいキーを別のキーやショートカットへ割り当てます。", provider: "powertoys" },
  { id: "app-shortcuts", result: "アプリごとにショートカットを変える", featureName: "Keyboard Manager", description: "特定のアプリを使っている間だけ、ショートカットの割り当てを変えます。", provider: "powertoys" },
  { id: "plain-paste", result: "貼り付けるとき書式を消す", featureName: "Paste as Plain Text", description: "色やフォントなどを外し、文字だけを貼り付けます。", provider: "powertoys" },
  { id: "ocr", result: "画面の文字を読み取る", featureName: "Text Extractor", description: "画面の範囲を選び、画像中の文字をクリップボードへ取り込みます。", provider: "powertoys" },
  { id: "always-on-top", result: "ウィンドウを常に手前へ置く", featureName: "Always On Top", description: "選んだウィンドウを、他のウィンドウの上に表示し続けます。", provider: "powertoys" },
  { id: "split-layouts", result: "画面分割の型を作る", featureName: "FancyZones", description: "よく使う分割レイアウトを作り、ウィンドウをその枠に配置しやすくします。", provider: "powertoys" },
  { id: "save-layout", result: "アプリ起動込みの作業環境を保存する", featureName: "Workspaces", description: "PowerToysは複数アプリの起動と配置をまとめます。現在開いているウィンドウの位置だけなら、上のPCカスタム配置保存を使います。", provider: "powertoys" },
  { id: "launch-apps", result: "複数アプリを一度に開く", featureName: "Workspaces", description: "保存した作業環境から、必要なアプリをまとめて起動します。", provider: "powertoys" },
  { id: "mouse-highlight", result: "マウスの位置を見つけやすくする", featureName: "Mouse Utilities", description: "Find My Mouseなどで、ポインターの位置やクリックを強調します。", provider: "powertoys" },
  { id: "clipboard-history", result: "クリップボード履歴を使う", featureName: "Windows 11 クリップボード履歴（PowerToys外）", description: "Windows標準の Win + V で、過去にコピーした項目を選びます。", provider: "windows" },
  { id: "resize-images", result: "画像を簡単に小さくする", featureName: "Image Resizer", description: "Explorerから画像を選び、決めた大きさへまとめてリサイズします。", provider: "powertoys" },
  { id: "batch-rename", result: "複数ファイルの名前をまとめて変える", featureName: "PowerRename", description: "Explorerから複数ファイルを選び、名前の置換や一括変更を行います。", provider: "powertoys" },
] as const satisfies readonly EverydayFeatureGuide[];

export const CATEGORIES = [
  { id: "session", label: "集中・セッション", description: "その場だけ有効にして、終われば解放", icon: "focus" },
  { id: "power", label: "電源", description: "現在の電源状態を確認", icon: "power" },
  { id: "explorer", label: "ファイル表示", description: "ファイルを見分けやすくする", icon: "explorer" },
  { id: "appearance", label: "見た目", description: "Windowsとアプリの明暗を揃える", icon: "appearance" },
  { id: "games", label: "ゲーム", description: "起動を見守り、プレイ中の邪魔を減らす", icon: "game" },
  { id: "setup", label: "セットアップ", description: "デバイスと日常の初期設定", icon: "action" },
  { id: "storage", label: "ストレージ", description: "空き容量と一時ファイルの状態を確認", icon: "info" },
  { id: "notifications", label: "通知", description: "必要なWindows通知の表示を選ぶ", icon: "info" },
  { id: "input", label: "入力", description: "タッチキーボードと入力候補の設定", icon: "focus" },
] as const satisfies readonly CategoryPresentation[];

export const RESULT_TILES = [
  { id: "everyday", title: "操作と普段使いの設定", description: "PowerToysとWindows標準機能で、日常操作を便利にします。", category: "setup-view", icon: "action" },
  { id: "game-ready", title: "ゲームを始める前の準備", description: "起動を検知し、邪魔を減らす準備をまとめます。", category: "games", icon: "game" },
  { id: "appearance", title: "見た目を変える", description: "Windowsとアプリを落ち着いた明暗へ揃えます。", category: "appearance", icon: "appearance" },
  { id: "files", title: "ファイルを見分けやすくする", description: "拡張子や隠しファイルを必要なときに表示します。", category: "explorer", icon: "explorer" },
  { id: "focus", title: "集中を途切れさせない", description: "作業中の自動スリープだけを一時的に防ぎます。", category: "session", icon: "focus" },
  { id: "power", title: "電源設定を確かめる", description: "変更せず、現在の電源プランを確認します。", category: "power", icon: "power" },
  { id: "study", title: "勉強・作業に集中する", description: "よく使う準備をまとめて、実行したいときだけ適用します。", category: "modes", icon: "focus" },
  { id: "setup", title: "新しいPCをセットアップする", description: "既定アプリ・音声・ウィンドウ配置と、よく使うアプリの導入をまとめます。", category: "setup-view", icon: "plus" },
  { id: "storage", title: "容量を空ける", description: "空き容量を確認し、古い一時ファイルだけを消せます。", category: "storage", icon: "info" },
  { id: "recovery", title: "変更を元へ戻す", description: "適用履歴から、戻したい項目だけを選べます。", category: "recovery", icon: "recovery" },
] as const satisfies readonly ResultTile[];

const BASE_STATIC_ACTIONS = [
  {
    id: "session.prevent_sleep",
    actionVersion: 1,
    name: "このモード中は自動スリープを防ぐ",
    description: "勉強、配信、長い処理の途中でPCが自動スリープへ入らないようにします。画面の常時点灯は既定で行いません。",
    audience: "作業中だけPCを起こしておきたい人向け",
    category: "session",
    tags: ["一時的", "公開API", "画面点灯なし"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: true,
    kind: "session",
    availability: "mutable",
    methodSummary: "Windows公開API SetThreadExecutionStateの専用lease",
    desiredState: "自動スリープを一時的に防ぐ（画面点灯なし）",
    detailPoints: [
      "最後のleaseを解放すると、PCカスタムの要求だけを解除します。",
      "PCカスタム終了時もOSが要求を解放します。",
      "他アプリのスリープ防止要求は変更しません。",
    ],
  },
  {
    id: "input.shift_interruption_guard",
    actionVersion: 1,
    name: "ゲーム中のShift確認画面を止める",
    description: "Shiftを5回押したときや右Shiftを長押ししたときに出る確認画面を、このモードの間だけ出さないようにします。入力の補助機能そのものは無効にしません。",
    audience: "ゲーム中にShift操作で確認画面へ割り込まれたくない人向け。入力の補助機能をShift操作から開く人には向きません",
    category: "games",
    tags: ["ゲーム", "Shift", "一時的"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: 26200,
    riskLevel: "caution",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: true,
    kind: "persistent",
    autoApplyEligible: true,
    availability: "mutable",
    methodClass: "public_api",
    methodSummary: "Windowsが公開している入力設定の機能で、確認画面を開く動作だけを一時停止",
    desiredState: "Shift操作による確認画面を、このモードの間だけ出さない",
    detailPoints: [
      "変えるのは、Shiftの連打・長押しから確認画面を開く動作だけです。",
      "入力を補助する機能そのものと、キーの待ち時間などは変更しません。",
      "入力の補助機能を現在使用中の場合は、安全のため適用しません。",
      "適用前の全設定を保存し、他の変更が無い場合だけ元の状態へ戻します。",
    ],
  },
  {
    id: "power.active_scheme_check",
    actionVersion: 1,
    name: "現在の電源設定を確認する",
    description: "現在アクティブな電源プランを読み取り専用で確認します。設定は変更しません。",
    audience: "ゲームや作業前に電源状態だけを確かめたい人向け",
    category: "power",
    tags: ["読み取り専用", "公開API"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "observation",
    availability: "read_only",
    methodSummary: "Windows公開Power APIによる読み取り",
    desiredState: "現在の電源プランを表示する（変更なし）",
    detailPoints: [
      "PowerGetActiveSchemeで構成値を読み取ります。",
      "OEM独自の状態は不明として表示する場合があります。",
      "読み取りのためrollback対象となる変更はありません。",
    ],
  },
  {
    id: "explorer.show_extensions",
    actionVersion: 1,
    name: "ファイルの拡張子を常に表示する",
    description: "画像、文書、実行ファイルなどの種類を名前の末尾で見分けやすくします。",
    audience: "似た名前のファイルを確実に見分けたい人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "拡張子を表示する",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "Explorerを強制再起動せず、設定変更通知で反映します。",
      "Windows Update後は再検証まで自動変更を止めます。",
    ],
  },
  {
    id: "explorer.show_hidden",
    actionVersion: 1,
    name: "隠しファイルを表示する",
    description: "通常は隠されているファイルをExplorerへ表示します。保護されたOSファイルの表示は変更しません。",
    audience: "設定ファイルを探す必要がある人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "保護OSファイル除外"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "caution",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "隠しファイルを表示する",
    detailPoints: [
      "表示されたファイルを誤って移動・削除しないよう注意が必要です。",
      "保護されたオペレーティングシステムファイルは対象外です。",
      "元々値が無ければ、復元時に削除して欠如状態へ戻します。",
    ],
  },
  {
    id: "explorer.clock_seconds",
    actionVersion: 1,
    name: "タスクバーの時計に秒を表示する",
    description: "タスクバー右下の時計に秒まで表示します。時刻をより細かく確認できます。",
    audience: "タスクバーの時計で秒まで確認したい人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "時計に秒を表示する",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "Explorerを強制再起動せず、設定変更通知で反映します。",
      "秒表示はバッテリーやCPUをわずかに使う場合があります。",
    ],
  },
  {
    id: "appearance.transparency",
    actionVersion: 1,
    name: "透明効果を切り替える",
    description: "スタートメニューやタスクバーの透明効果のオン・オフを切り替えます。",
    audience: "透明効果のオン・オフを切り替えたい人向け",
    category: "appearance",
    tags: ["HKCU", "Personalize", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Themes\\Personalizeの限定値をbackup後に変更し、通知で反映",
    desiredState: "選択した透明効果の状態",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "システム面と対応アプリの透明効果に影響します。",
      "元々値が無ければ、復元時に削除して欠如状態へ戻します。",
    ],
  },
  {
    id: "taskbar.task_view",
    actionVersion: 1,
    name: "タスクビューボタンを表示・非表示",
    description: "タスクバーのタスクビューボタンを出すか消すかを選びます。反映にはエクスプローラーの再起動が必要です。",
    audience: "タスクビューボタンの表示を切り替えたい人向け",
    category: "appearance",
    tags: ["HKCU", "Explorer", "タスクバー"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "選択したタスクビューボタンの表示",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "タスクバー系はWindows更新で挙動が変わり得ます。",
      "更新後は再検証まで自動変更を止めます。",
    ],
  },
  {
    id: "taskbar.widgets",
    actionVersion: 1,
    name: "ウィジェットボタンを表示・非表示",
    description: "タスクバー左端の天気やニュースのウィジェットを出すか消すかを選びます。反映にはエクスプローラーの再起動が必要です。",
    audience: "ウィジェットボタンの表示を切り替えたい人向け",
    category: "appearance",
    tags: ["HKCU", "Explorer", "タスクバー"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "caution",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "選択したウィジェットボタンの表示",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "ウィジェット系はWindows更新でキーや挙動が変わり得ます。",
      "更新後は再検証まで自動変更を止めます。",
    ],
  },
  {
    id: "explorer.item_checkboxes",
    actionVersion: 1,
    name: "項目チェックボックスを表示・非表示",
    description: "Explorerでファイルやフォルダーを選ぶチェックボックスの表示を切り替えます。",
    audience: "チェックボックスでの複数選択を切り替えたい人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "選択した項目チェックボックスの表示",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "チェックボックスでファイルを複数選びやすくなります。",
      "元々値が無ければ、復元時に削除して欠如状態へ戻します。",
    ],
  },
  {
    id: "explorer.compact_view",
    actionVersion: 1,
    name: "コンパクト表示を切り替える",
    description: "Explorerの一覧の行間を詰めるコンパクト表示のオン・オフを切り替えます。",
    audience: "一覧の行間（コンパクト表示）を切り替えたい人向け",
    category: "explorer",
    tags: ["HKCU", "Explorer", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Explorer\\Advancedの限定値をbackup後に変更し、非破壊通知で反映",
    desiredState: "選択したコンパクト表示の状態",
    detailPoints: [
      "元の値の有無、型、生データを保存してから変更します。",
      "行間が詰まり、一画面に多くの項目を表示できます。",
      "元々値が無ければ、復元時に削除して欠如状態へ戻します。",
    ],
  },
  {
    id: "theme.color_mode",
    actionVersion: 1,
    name: "Windowsとアプリをダーク表示にする",
    description: "Windowsのシステム面と対応アプリを、落ち着いたダーク表示へ揃えます。",
    audience: "暗い環境で明るさを抑えたい人向け",
    category: "appearance",
    tags: ["HKCU", "2項目を一括復元", "実機スモーク前提"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: true,
    kind: "persistent",
    availability: "mutable",
    methodSummary: "HKCU Themes\\Personalizeの2値を複合Actionとして保存・変更",
    desiredState: "Windowsと対応アプリをダーク表示にする",
    detailPoints: [
      "アプリ用とシステム用の2値をまとめてbackupします。",
      "ハイコントラストや組織ポリシーと競合する場合は変更しません。",
      "一部のアプリでは再起動後に表示が変わります。",
    ],
  },
  {
    id: "games.process_watch",
    actionVersion: 1,
    name: "登録したゲームの起動・終了を検知する",
    description: "登録した実行ファイルが同じものであることを確かめてから、起動と終了だけを見守ります。ゲームへの注入や改変はしません。",
    audience: "ゲームごとの準備を将来自動化したい人向け",
    category: "games",
    tags: ["読み取り専用", "注入なし", "同一ファイル確認"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "observation",
    availability: "read_only",
    methodSummary: "Toolhelp snapshot、process path、PID、creation time、file identityの照合",
    desiredState: "登録した実行ファイルと同じものだと確かめられたゲームだけを見守る（OS変更なし）",
    currentState: {
      kind: "unknown",
      label: "実行ファイル未登録",
      detail: "モードで実行ファイルを登録した後に、path・作成時刻・file identityを照合します。",
    },
    detailPoints: [
      "process名だけでなく、pathと作成時刻を照合します。",
      "アクセス拒否時は未実行と推測せず、状態不明として扱います。",
      "ゲームprocessやファイルへ書き込み・注入を行いません。",
    ],
  },
] as const satisfies readonly ActionPresentation[];

interface RegistryFallbackDefinition {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly category: ActionPresentation["category"];
  readonly riskLevel: ActionPresentation["riskLevel"];
  readonly desiredState: string;
}

const REGISTRY_FALLBACKS = [
  {
    id: "taskbar.search_mode",
    name: "タスクバー検索の表示方法を選ぶ",
    description: "検索を隠す、アイコンだけ、ラベル付き、検索ボックスから選びます。反映にはエクスプローラーの再起動が必要です。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "検索ボックスを表示する",
  },
  {
    id: "taskbar.alignment",
    name: "タスクバーを左寄せ／中央寄せにする",
    description: "スタートボタンとアイコンを左端か中央に置きます。反映にはエクスプローラーの再起動が必要です。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "タスクバーを左寄せにする",
  },
  {
    id: "start.layout",
    name: "スタートのピンとおすすめの比率を選ぶ",
    description: "既定、ピンを増やす、おすすめを増やすから選びます。Microsoft公開の0〜2値だけを使用します。",
    category: "appearance",
    riskLevel: "safe",
    desiredState: "スタートのピンを増やす",
  },
  {
    id: "start.recommendations",
    name: "スタートのヒントや新しいアプリのおすすめを減らす",
    description: "おすすめ機能の表示だけを切り替え、ピンやインストール済みアプリは変更しません。",
    category: "appearance",
    riskLevel: "safe",
    desiredState: "ヒントやおすすめを表示しない",
  },
  {
    id: "explorer.launch_target",
    name: "Explorerを開いたときの場所を選ぶ",
    description: "ホーム、PC、ダウンロードから開始場所を選びます。既存ウィンドウの位置は変更しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "ExplorerをPCから開く",
  },
  {
    id: "explorer.recent_files",
    name: "Explorerに最近使ったファイルを表示する",
    description: "Explorerの最近使ったファイル欄だけを切り替え、履歴ファイル自体は削除しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "最近使ったファイルを表示する",
  },
  {
    id: "taskbar.button_grouping",
    name: "タスクバーのボタン結合方法を選ぶ",
    description: "常に結合、いっぱいのとき、結合しないから選びます。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "タスクバーがいっぱいのときにボタンを結合する",
  },
  {
    id: "taskbar.flashing",
    name: "タスクバーアプリの点滅通知を切り替える",
    description: "注意が必要なアプリがタスクバーで点滅する表示だけを切り替えます。通知自体は削除しません。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "タスクバーの点滅通知を有効にする",
  },
  {
    id: "taskbar.share_window",
    name: "タスクバーからウィンドウを共有できるようにする",
    description: "対応する会議アプリで、タスクバーからウィンドウ共有を選べる表示を切り替えます。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "タスクバーからのウィンドウ共有を有効にする",
  },
  {
    id: "taskbar.show_desktop",
    name: "タスクバー右端のデスクトップ表示を切り替える",
    description: "タスクバー右端の、押すとデスクトップが見える細い領域を出すか消すかを選びます。反映にはエクスプローラーの再起動が必要です。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "タスクバー右端のデスクトップ表示を有効にする",
  },
  {
    id: "search.recent_on_hover",
    name: "検索アイコンに触れたときの最近の検索表示を切り替える",
    description: "検索アイコンへポインターを置いたときに最近の検索を開く動作を切り替えます。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "ポインターを置いても最近の検索を開かない",
  },
  {
    id: "taskbar.multi_monitor",
    name: "すべてのモニターにタスクバーを表示する",
    description: "複数ディスプレイでタスクバーを表示するかを切り替えます。単一ディスプレイでは効果がありません。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "すべてのモニターにタスクバーを表示する",
  },
  {
    id: "taskbar.multi_monitor_mode",
    name: "複数モニターでアプリボタンを出す場所を選ぶ",
    description: "すべて、メインとウィンドウのある画面、ウィンドウのある画面から選びます。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "ウィンドウのあるモニターにアプリボタンを表示する",
  },
  {
    id: "taskbar.secondary_button_grouping",
    name: "別モニターのタスクバーボタン結合方法を選ぶ",
    description: "セカンダリーモニターのボタンを、常に結合、いっぱいのとき、結合しないから選びます。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "別モニターのタスクバーがいっぱいのときにボタンを結合する",
  },
  {
    id: "start.show_all_pins",
    name: "スタートですべてのピンを最初に表示する",
    description: "スタートを開いたとき、すべてのピン一覧を先に表示するかを切り替えます。ピン内容は変更しません。",
    category: "appearance",
    riskLevel: "safe",
    desiredState: "すべてのピン一覧を最初に表示する",
  },
  {
    id: "start.recent_apps",
    name: "スタートに最近追加したアプリを表示する",
    description: "最近インストールしたアプリの一覧表示だけを切り替え、アプリ自体は変更しません。",
    category: "appearance",
    riskLevel: "safe",
    desiredState: "最近追加したアプリを表示する",
  },
  {
    id: "appearance.accent_start_taskbar",
    name: "スタートとタスクバーにアクセント色を表示する",
    description: "選択済みのWindowsアクセント色をスタートとタスクバーへ表示するかを切り替えます。色そのものは変更しません。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "スタートとタスクバーにアクセント色を表示する",
  },
  {
    id: "appearance.accent_title_bars",
    name: "タイトルバーとウィンドウ枠にアクセント色を表示する",
    description: "選択済みのアクセント色を対応するタイトルバーとウィンドウ枠へ表示するかを切り替えます。",
    category: "appearance",
    riskLevel: "safe",
    desiredState: "タイトルバーとウィンドウ枠にアクセント色を表示する",
  },
  {
    id: "appearance.auto_accent",
    name: "背景に合わせてアクセント色を自動選択する",
    description: "デスクトップ背景に合わせたWindowsの自動アクセント選択を切り替えます。任意色の直接書込みは行いません。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "背景に合わせたアクセント色の自動選択を有効にする",
  },
  {
    id: "games.game_mode",
    name: "Windows Game Modeを切り替える",
    description: "Windows標準のGame Mode設定だけを切り替えます。サービス停止やゲーム改変は行いません。",
    category: "games",
    riskLevel: "caution",
    desiredState: "Windows Game Modeを有効にする",
  },
  {
    id: "games.controller_game_bar",
    name: "コントローラーからGame Barを開く操作を切り替える",
    description: "コントローラーのXboxボタンでGame Barを開く設定だけを切り替えます。入力の注入は行いません。",
    category: "games",
    riskLevel: "safe",
    desiredState: "コントローラーからGame Barを開かない",
  },
  {
    id: "devices.autoplay",
    name: "メディアとデバイスの自動再生を切り替える",
    description: "リムーバブルメディアの自動再生マスター設定を切り替えます。個別の既定アプリは変更しません。",
    category: "setup",
    riskLevel: "safe",
    desiredState: "メディアとデバイスの自動再生を有効にする",
  },
  {
    id: "notifications.usb_errors",
    name: "USBエラーの通知を表示する",
    description: "USB接続エラーのWindows通知だけを切り替えます。USB機能やドライバーは変更しません。",
    category: "notifications",
    riskLevel: "safe",
    desiredState: "USBエラー通知を表示する",
  },
  {
    id: "notifications.weak_charger",
    name: "低出力充電器の通知を表示する",
    description: "充電器の出力不足を知らせるWindows通知だけを切り替えます。充電制御は変更しません。",
    category: "notifications",
    riskLevel: "safe",
    desiredState: "低出力充電器の通知を表示する",
  },
  {
    id: "input.autocorrect",
    name: "タッチキーボードの自動修正を切り替える",
    description: "Windowsのタッチ入力に対する自動修正だけを切り替えます。物理キーボードの配列は変更しません。",
    category: "input",
    riskLevel: "safe",
    desiredState: "タッチキーボードの自動修正を有効にする",
  },
  {
    id: "input.double_space_period",
    name: "スペース2回でピリオドを入力する",
    description: "タッチキーボードでスペースを2回押したときのピリオド入力を切り替えます。",
    category: "input",
    riskLevel: "safe",
    desiredState: "スペース2回のピリオド入力を有効にする",
  },
  {
    id: "input.auto_shift",
    name: "タッチキーボードの自動Shiftを切り替える",
    description: "文頭などでタッチキーボードがShiftを自動的に有効にする動作を切り替えます。",
    category: "input",
    riskLevel: "safe",
    desiredState: "タッチキーボードの自動Shiftを有効にする",
  },
  {
    id: "input.voice_typing_key",
    name: "音声入力キーを表示する",
    description: "タッチキーボードの音声入力キー表示だけを切り替えます。マイク権限は変更しません。",
    category: "input",
    riskLevel: "safe",
    desiredState: "タッチキーボードに音声入力キーを表示する",
  },
  {
    id: "input.multilingual_suggestions",
    name: "多言語の入力候補を切り替える",
    description: "Windowsの多言語入力候補を切り替えます。インストール済み言語や辞書は変更しません。",
    category: "input",
    riskLevel: "safe",
    desiredState: "多言語の入力候補を有効にする",
  },
  {
    id: "explorer.status_bar",
    name: "Explorerのステータスバーを表示する",
    description: "Explorer下部の項目数などを示すステータスバー表示を切り替えます。ファイルには触れません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "Explorerのステータスバーを表示する",
  },
  {
    id: "explorer.info_tips",
    name: "Explorerのファイル説明を表示する",
    description: "ファイルへポインターを置いたときの説明表示を切り替えます。ファイル内容は変更しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "Explorerのファイル説明を表示する",
  },
  {
    id: "explorer.hide_empty_drives",
    name: "空のリムーバブルドライブを隠す",
    description: "メディアが入っていないリムーバブルドライブの表示だけを切り替えます。ドライブは無効化しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "空のリムーバブルドライブを隠す",
  },
  {
    id: "explorer.nav_expand_current",
    name: "ナビゲーションを現在のフォルダーまで展開する",
    description: "Explorer左側のナビゲーションを現在位置まで自動展開する動作を切り替えます。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "ナビゲーションを現在のフォルダーまで自動展開する",
  },
  {
    id: "explorer.nav_show_all",
    name: "ナビゲーションにすべてのフォルダーを表示する",
    description: "Explorer左側のナビゲーションにすべてのフォルダーを出す表示を切り替えます。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "ナビゲーションにすべてのフォルダーを表示する",
  },
  {
    id: "explorer.separate_process",
    name: "フォルダーウィンドウを別プロセスで開く",
    description: "Explorerのフォルダーウィンドウ分離設定を切り替えます。既存プロセスの強制終了は行いません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "フォルダーウィンドウを別プロセスで開く",
  },
  {
    id: "explorer.icons_only",
    name: "サムネイルを使わず常にアイコンを表示する",
    description: "Explorerのサムネイル表示をアイコンだけに切り替えます。サムネイルキャッシュは削除しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "サムネイルを表示する",
  },
  {
    id: "explorer.drive_letters",
    name: "Explorerにドライブ文字を表示する",
    description: "ドライブ名の横にC:などのドライブ文字を表示する設定を切り替えます。割り当て自体は変更しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "Explorerにドライブ文字を表示する",
  },
  {
    id: "explorer.preview_handlers",
    name: "プレビューウィンドウでファイル内容を表示する",
    description: "登録済みプレビューハンドラーの利用を切り替えます。ハンドラーの追加や任意DLL実行は行いません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "登録済みプレビューハンドラーを使用する",
  },
  {
    id: "explorer.sharing_wizard",
    name: "Explorerの共有ウィザードを使う",
    description: "ファイル共有の案内ウィザード表示を切り替えます。共有権限やネットワーク設定は変更しません。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "Explorerの共有ウィザードを使用する",
  },
  {
    id: "explorer.always_show_menus",
    name: "Explorerのメニューを常に表示する",
    description: "従来形式のメニュー表示に対応する固定HKCU値を切り替えます。Windows UIへの反映は実機確認まで明示操作のみです。",
    category: "explorer",
    riskLevel: "caution",
    desiredState: "Explorerのメニューを常に表示する",
  },
  {
    id: "appearance.taskbar_animations",
    name: "タスクバーのアニメーションを切り替える",
    description: "タスクバーの視覚アニメーションだけを切り替えます。DWM、サービス、性能設定の一括変更は行いません。",
    category: "appearance",
    riskLevel: "caution",
    desiredState: "タスクバーのアニメーションを有効にする",
  },
  {
    id: "notifications.toast_banners",
    name: "Windowsの通知バナーを切り替える",
    description: "ユーザー全体の通知バナー表示を明示的に切り替えます。Windows SecurityやUpdateの機能は停止しません。",
    category: "notifications",
    riskLevel: "caution",
    desiredState: "Windowsの通知バナーを表示する",
  },
] as const satisfies readonly RegistryFallbackDefinition[];

function registryFallback(definition: RegistryFallbackDefinition): ActionPresentation {
  return {
    id: definition.id,
    actionVersion: 1,
    name: `設計候補: ${definition.name}`,
    description: "Windowsが保存している設定値を読み取って表示するだけです。書き換えても画面が変わることを実機で確かめられていないため、変更はしません。",
    audience: "いまWindowsに何が保存されているかを確認したい人向け",
    category: definition.category,
    tags: ["HKCU", "保存値観測", "根拠確認待ち"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: null,
    riskLevel: "experimental",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "review",
    reversible: false,
    kind: "guided",
    autoApplyEligible: false,
    availability: "read_only",
    methodClass: "unverified_storage",
    methodSummary: "未立証の固定HKCU保存値を読み取るのみ（setter設計は承認待ち）",
    desiredState: "実機で反映を確かめられるまで保留（変更は実行しません）",
    detailPoints: [
      "setterの一次資料と対象buildの実機UI試験が未承認のため、変更処理を実行しません。",
      "表示するのは固定HKCU DWORDの保存値であり、Windows UIの有効状態を示しません。",
      "変更を求められても、処理のどの段階でも拒否します。",
      "ゲームモードの自動適用対象にはしません。",
    ],
  };
}

interface ObservationFallbackDefinition {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly audience: string;
  readonly category: ActionPresentation["category"];
  readonly tags: readonly string[];
  readonly methodSummary: string;
  readonly desiredState: string;
  readonly detailPoints: readonly string[];
}

type AdditionalFallbackDefinition = ObservationFallbackDefinition | ActionPresentation;

const OBSERVATION_FALLBACKS = [
  {
    id: "setup.startup_inventory",
    name: "スタートアップ項目を確認する",
    description: "HKCU/HKLMの固定RunキーとWindowsのユーザー/共通Startupフォルダーを、変更せず上限付きで一覧化します。",
    audience: "固定RunキーとStartupフォルダーの登録項目を、無効化せず確認したい人向け",
    category: "setup",
    tags: ["スタートアップ", "固定Runキー", "読み取り専用"],
    methodSummary: "固定HKCU/HKLM Runキー、Known Folder、上限付きフォルダー列挙による読み取り",
    desiredState: "確認対象のスタートアップ項目を一覧表示する（変更なし）",
    detailPoints: [
      "登録済みのRunキーとWindowsのKnown Startupフォルダーだけを確認します。",
      "コマンド本文は保持も実行もせず、項目名・場所・値の状態だけを表示します。",
      "確認対象のスタートアップ項目の無効化、削除、書き換えは行いません。",
    ],
  },
  {
    id: "power.active_scheme_switch",
    actionVersion: 1,
    name: "電源プランを明示的に切り替える",
    description: "Windows公開Power APIで、バランス・省電力・高パフォーマンスの固定候補から現在ユーザーの電源プランを選びます。FPS向上は保証しません。",
    audience: "電源プランを自分で明示的に選びたい人向け",
    category: "power",
    tags: ["公開API", "明示操作", "固定候補"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2"],
    minimumBuild: 26100,
    maximumTestedBuild: 26200,
    riskLevel: "caution",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: true,
    kind: "persistent",
    autoApplyEligible: false,
    availability: "mutable",
    methodClass: "public_api",
    methodSummary: "PowerGetActiveSchemeとPowerSetActiveScheme",
    desiredState: "選択したWindows標準の電源プラン",
    detailPoints: [
      "適用前のactive scheme GUIDを型付きで保存します。",
      "復元時に別の電源プランへ変わっていた場合は上書きしません。",
      "ゲームモードの無人適用対象にはしません。",
    ],
  },
  {
    id: "storage.free_space_check",
    name: "システムドライブの空き容量を確認する",
    description: "Windowsの公開APIでシステムドライブの総容量と利用可能容量を読み取るだけです。",
    audience: "インストールやゲーム開始前に空き容量だけを確認したい人向け",
    category: "storage",
    tags: ["ストレージ", "空き容量", "読み取り専用"],
    methodSummary: "GetWindowsDirectoryWとGetDiskFreeSpaceExWによる読み取り",
    desiredState: "システムドライブの容量を表示する（変更なし）",
    detailPoints: [
      "Windowsが使用するシステムドライブを公開APIで特定します。",
      "総容量、全体の空き、現在のユーザーが利用できる空きを表示します。",
      "ファイルの作成、移動、削除は行いません。",
    ],
  },
  {
    id: "storage.temp_files_check",
    name: "一時ファイルの使用量を確認する",
    description: "Windowsが返すユーザー一時フォルダーを、reparse pointを追跡せず件数・深さ・時間・合計量の上限内で集計します。削除はしません。",
    audience: "削除せずに一時ファイルの規模だけを確認したい人向け",
    category: "storage",
    tags: ["ストレージ", "一時ファイル", "読み取り専用"],
    methodSummary: "GetTempPath2Wとreparse point非追跡の上限付きmetadata走査",
    desiredState: "一時ファイルの件数と合計サイズを表示する（変更なし）",
    detailPoints: [
      "Windowsが返した現在ユーザーの一時フォルダーだけを対象にします。",
      "reparse pointを追跡せず、件数・深さ・時間・合計量に上限を設けます。",
      "ファイル内容の確認や削除は行いません。",
    ],
  },
  {
    id: "games.readiness_check",
    name: "ゲーム前の確認情報を表示する",
    description: "Hz、Advanced Color、電源、空き容量、既定の音声出力を確認し、Game Modeと通知は固定HKCU登録値を設定の目安として表示します。Advanced ColorをHDRの実効状態とは断定しません。",
    audience: "ゲーム開始前にWindowsの参考情報を一度に確認したい人向け",
    category: "games",
    tags: ["ゲーム準備", "7項目", "読み取り専用"],
    methodSummary: "Windows公開APIと登録済み固定HKCU設定値による読み取り専用の合成確認",
    desiredState: "ゲーム前の参考情報7項目をまとめて表示する（変更なし）",
    detailPoints: [
      "リフレッシュレート、Advanced Color、電源、空き容量、音声を独立して確認します。Advanced ColorはHDRの実効状態とは断定しません。",
      "Game Modeと通知は固定HKCU登録値を設定の目安として表示し、実際の有効状態とは断定しません。",
      "取得できない項目は推測せず、不明または未設定として表示します。",
      "電源、表示、音声、通知を変更せず、ゲームへの注入も行いません。",
    ],
  },
  {
    id: "appearance.accent_color_check",
    name: "いまのアクセントカラーを確認する",
    description: "Windowsが現在使っている色を、公開APIで読み取るだけです。色の変更は行いません。",
    audience: "いまWindowsが使っている色を、変更せずに確かめたい人向け",
    category: "appearance",
    tags: ["見た目", "アクセントカラー", "読み取り専用"],
    methodSummary: "公開APIのDwmGetColorizationColorによる読み取り",
    desiredState: "いまWindowsが使っている色を表示する（変更なし）",
    detailPoints: [
      "読み取り専用で、Windowsの設定や配色は変更しません。",
      "取得できない場合は推測せず、不明として扱います。",
      "アクセントカラーの変更は、実機で反映を確かめられるまで行いません。",
    ],
  },
  {
    id: "appearance.window_color",
    name: "ウィンドウの色を変える",
    description: "タイトルバーなどに使われる色を、決められた色から選んで変えます。元の色は正確に戻せます。",
    audience: "タイトルバーなどの色を、決められた色から選んで変えたい人向け",
    category: "appearance",
    tags: ["見た目", "色", "DWM"],
    methodSummary: "HKCU DWMの色2値を1トランザクションで変更",
    desiredState: "選んだ色をウィンドウに使う",
    detailPoints: [
      "変更するのは決められた2つの色設定だけで、任意の色は受け取りません。",
      "2つの値を1つの変更としてまとめ、片方だけ変わった状態を残しません。",
      "元の色・型・有無を保存し、他アプリが変更していた場合は上書きしません。",
    ],
  },
  {
    id: "setup.powertoys_status",
    name: "PowerToysの導入状況を確認する",
    description: "Windowsの文書化されたApp Paths登録だけでPowerToysの導入状況を確認します。設定ファイルは読み書きしません。",
    audience: "日常のWindows操作をPowerToysで便利にしたい人向け",
    category: "setup",
    tags: ["PowerToys", "App Paths", "読み取り専用"],
    methodSummary: "文書化されたApp Paths登録とアンインストール登録の読み取り",
    desiredState: "PowerToysの導入状況とバージョンを表示する（変更なし）",
    detailPoints: [
      "PowerToys.exeの固定App Paths登録と実ファイルを確認します。",
      "バージョンはMicrosoftのアンインストール登録から取得できた場合だけ表示します。",
      "PowerToysの設定ファイルは読み書きしません。",
    ],
  },
  {
    id: "setup.launch_apps",
    actionVersion: 1,
    name: "決めたアプリをまとめて開く",
    description: "固定リストの学習・作業用アプリだけを、シェルを介さず直接開きます。起動したアプリは復元時にも終了しません。",
    audience: "勉強や作業を始めるアプリを一度に開きたい人向け",
    category: "setup",
    tags: ["アプリ起動", "固定allowlist", "手動のみ"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2", "Windows 11 26H1"],
    minimumBuild: 22631,
    maximumTestedBuild: 26200,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "one_way",
    autoApplyEligible: false,
    availability: "mutable",
    methodClass: "public_api",
    methodSummary: "App Pathsと固定System32候補を検証し、shell非経由で直接起動",
    desiredState: "固定allowlistのアプリを、起動中でなければ直接開く",
    detailPoints: [
      "任意パス・任意アプリID・ユーザー引数は受け付けません。",
      "起動中のプロセス名を確認し、二重起動しません。",
      "起動したアプリを勝手に終了しないため、元に戻せません。",
    ],
  },
  {
    id: "setup.windows_update_status",
    name: "Windows Updateの確認状況を見る",
    description: "Windows Update Agentで最後の確認日時と再起動保留だけを読み取ります。Updateは変更しません。",
    audience: "更新確認日時と再起動保留だけを変更せず確認したい人向け",
    category: "setup",
    tags: ["Windows Update", "再起動", "読み取り専用"],
    methodSummary: "Windows Update Agent公開COMプロパティの読み取り",
    desiredState: "Windows Update Agentの状態を変更せず確認",
    detailPoints: [
      "最後に更新を確認できた日時と再起動保留だけを読み取ります。",
      "取得できない項目は推測せず、不明と表示します。",
      "Windows Updateの停止・設定変更・検索開始は行いません。",
    ],
  },
  {
    id: "setup.default_apps",
    actionVersion: 1,
    name: "既定のアプリを選ぶ",
    description: "ファイルやリンクを開くアプリを選ぶWindows設定へ案内します。PCカスタムは、Windowsが既定のアプリを覚えている場所を直接書き換えません。",
    audience: "ブラウザーやファイル種類ごとの既定アプリを自分で選びたい人向け",
    category: "setup",
    tags: ["Windows設定", "既定のアプリ", "案内のみ"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2", "Windows 11 26H1"],
    minimumBuild: 22631,
    maximumTestedBuild: 26200,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "guided",
    autoApplyEligible: false,
    availability: "read_only",
    methodClass: "public_api",
    methodSummary: "Windowsの「既定のアプリ」画面を開き、選択はWindowsに任せる",
    desiredState: "Windowsの「既定のアプリ」で利用者が選ぶ",
    detailPoints: [
      "Windowsは既定のアプリの記録に改ざん検出用の符号を付けており、外から書き換える正規の方法がありません。",
      "この項目は表示だけを行い、OSの設定は変更しません。",
      "設定画面を開いた後の選択は利用者がWindows上で行います。",
    ],
    settingsPage: "ms-settings:defaultapps",
  },
  {
    id: "setup.window_layout",
    actionVersion: 1,
    name: "現在のウィンドウ配置を保存・復元する",
    description: "今開いている対象ウィンドウの位置と表示状態を明示的に保存し、確認後に復元します。アプリは起動しません。",
    audience: "作業中のウィンドウを、いまの配置へ戻したい人向け",
    category: "setup",
    tags: ["ウィンドウ配置", "公開API", "明示保存"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2", "Windows 11 26H1"],
    minimumBuild: 22631,
    maximumTestedBuild: 26200,
    riskLevel: "caution",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: true,
    kind: "persistent",
    autoApplyEligible: false,
    availability: "mutable",
    methodClass: "public_api",
    methodSummary: "EnumWindows・GetWindowPlacement・SetWindowPlacementによる上限付きの保存と復元",
    desiredState: "明示的に保存した対象ウィンドウの位置と最小化・最大化状態へ戻す",
    detailPoints: [
      "保存時点で開いている対象ウィンドウだけを扱い、閉じたアプリを起動しません。",
      "登録済みゲーム、全画面表示、標準的でないウィンドウは対象外です。",
      "復元できない対象は勝手に代替せず、アプリ名だけで報告します。",
    ],
  },
  {
    id: "setup.audio_output",
    actionVersion: 1,
    name: "音声の出力先を確認する",
    description: "Windows公開MMDevice APIで接続中の音声出力と既定デバイスを確認し、切り替えはWindows設定へ案内します。",
    audience: "スピーカーやヘッドセットの接続と既定の出力先を確認したい人向け",
    category: "setup",
    tags: ["音声出力", "公開API", "Windows設定"],
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2", "Windows 11 26H1"],
    minimumBuild: 22631,
    maximumTestedBuild: 26200,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "guided",
    autoApplyEligible: false,
    availability: "read_only",
    methodClass: "public_api",
    methodSummary: "Windows公開の機能で接続中の音声出力を読み取り、切り替えはWindowsのサウンド設定へ案内",
    desiredState: "Windowsのサウンド設定で利用者が出力先を選ぶ",
    detailPoints: [
      "アクティブな音声出力と、現在の既定デバイスを公開APIで確認します。",
      "内部のendpoint IDは表示・記録せず、利用者向けのデバイス名だけを表示します。",
      "PCカスタムは既定デバイスを変更せず、Windowsのサウンド設定を開きます。",
    ],
    settingsPage: "ms-settings:sound",
  },
] as const satisfies readonly AdditionalFallbackDefinition[];

function observationFallback(definition: AdditionalFallbackDefinition): ActionPresentation {
  if ("actionVersion" in definition) {
    return definition;
  }
  return {
    id: definition.id,
    actionVersion: 1,
    name: definition.name,
    description: definition.description,
    audience: definition.audience,
    category: definition.category,
    tags: definition.tags,
    supportedWindowsVersions: ["Windows 11 24H2", "Windows 11 25H2", "Windows 11 26H1"],
    minimumBuild: 22631,
    maximumTestedBuild: 26200,
    riskLevel: "safe",
    requiresAdmin: false,
    requiresRestart: false,
    requiresExplorerRestart: false,
    updateImpact: "low",
    reversible: false,
    kind: "observation",
    autoApplyEligible: false,
    availability: "read_only",
    methodSummary: definition.methodSummary,
    desiredState: definition.desiredState,
    detailPoints: definition.detailPoints,
  };
}

export const STATIC_ACTIONS: readonly ActionPresentation[] = [
  ...BASE_STATIC_ACTIONS,
  ...REGISTRY_FALLBACKS.map(registryFallback),
  ...OBSERVATION_FALLBACKS.map(observationFallback),
];
